
import { Language } from './types';

export const UI_TEXT = {
  tr: {
    sidebarTitle: 'Cloudflare',
    sidebarSubtitle: 'MasterClass',
    searchPlaceholder: 'Konu veya araç ara...',
    processing: 'İşleniyor',
    queued: 'Sırada',
    resultsNotFound: 'Sonuç bulunamadı',
    settingsTitle: 'Ayarlar & Araçlar',
    settingsClose: 'Kapat',
    
    // Settings Actions
    refreshCategory: 'Kategoriyi Yenile',
    refreshCategoryDesc: 'Aktif kategorideki tüm konuları sıraya alır.',
    refreshAll: 'Tümünü Yenile',
    refreshAllDesc: 'Tüm müfredatı AI ile yeniden oluşturur.',
    resetProgress: 'İlerlemeyi Sıfırla',
    resetProgressDesc: 'Okundu işaretlerini temizler.',
    factoryReset: 'Fabrika Ayarlarına Dön',
    factoryResetDesc: 'Tüm AI içeriklerini siler ve varsayılana döner.',
    
    // Top Bar
    currentlyViewing: 'Şu an inceleniyor',
    statusRegenerating: 'YENİLENİYOR...',
    statusQueued: 'SIRADA...',
    btnRegenerate: 'YENİLE',
    btnProcessing: 'İŞLENİYOR',
    btnDownloadPdf: 'PDF İNDİR',
    btnComplete: 'TAMAMLA',
    btnCompleted: 'TAMAMLANDI',

    // Main Content
    welcomeTitle: 'Cloudflare',
    welcomeSubtitle: 'MasterClass',
    welcomeDesc: 'İnternet altyapısının geleceğini şekillendiren teknolojileri öğrenin.',
    loadingAI: 'İçerik Hazırlanıyor...',
    loadingQueue: 'Sırada Bekliyor...',
    loadingDesc: 'Cloudflare AI modelleri sizin için en güncel bilgileri derliyor. Bu sırada diğer konulara göz atabilirsiniz.',
    backgroundProcess: 'Arka planda daha yeni bir versiyon hazırlanıyor...',
    generatedBy: 'Cloudflare MasterClass AI tarafından üretildi',

    // Chat
    chatTitle: 'Cloudflare Asistanı',
    chatPlaceholder: 'Bir soru sorun...',
    chatEmpty: 'İçerikle ilgili takıldığınız yerleri sorun.',
    quoteSelection: '+ Seçimi Alıntıla',

    // Toasts
    toastReady: 'İçerik Hazır',
    toastReadyDesc: 'başarıyla oluşturuldu.',
    toastError: 'Hata',
    toastErrorDesc: 'oluşturulamadı.',
    toastQueued: 'Sıraya Alındı',
    toastQueuedDesc: 'güncellenmek üzere sıraya eklendi.',
    toastBulkCat: 'Kategori Güncelleniyor',
    toastBulkCatDesc: 'konu sıraya eklendi.',
    toastBulkAll: 'Tam Yenileme Başlatıldı',
    toastBulkAllDesc: 'konu sıraya alındı. Bu işlem zaman alabilir.',
    toastReset: 'Fabrika Ayarlarına Dönüldü',
    toastResetDesc: 'Tüm içerikler varsayılan (hızlı) haline getirildi.',
    toastResetProg: 'İlerleme Sıfırlandı',
    toastQueueCleared: 'Kuyruk Temizlendi'
  },
  en: {
    sidebarTitle: 'Cloudflare',
    sidebarSubtitle: 'MasterClass',
    searchPlaceholder: 'Search topics or tools...',
    processing: 'Processing',
    queued: 'Queued',
    resultsNotFound: 'No results found',
    settingsTitle: 'Settings & Tools',
    settingsClose: 'Close',

    // Settings Actions
    refreshCategory: 'Refresh Category',
    refreshCategoryDesc: 'Queues all topics in the active category.',
    refreshAll: 'Refresh All',
    refreshAllDesc: 'Regenerates the entire curriculum with AI.',
    resetProgress: 'Reset Progress',
    resetProgressDesc: 'Clears all read markers.',
    factoryReset: 'Factory Reset',
    factoryResetDesc: 'Deletes all AI content and reverts to default.',

    // Top Bar
    currentlyViewing: 'Currently Viewing',
    statusRegenerating: 'REGENERATING...',
    statusQueued: 'QUEUED...',
    btnRegenerate: 'REGENERATE',
    btnProcessing: 'PROCESSING',
    btnDownloadPdf: 'DOWNLOAD PDF',
    btnComplete: 'COMPLETE',
    btnCompleted: 'COMPLETED',

    // Main Content
    welcomeTitle: 'Cloudflare',
    welcomeSubtitle: 'MasterClass',
    welcomeDesc: 'Master the technologies shaping the future of the internet.',
    loadingAI: 'Generating Content...',
    loadingQueue: 'Waiting in Queue...',
    loadingDesc: 'Cloudflare AI models are compiling the latest information for you. You can browse other topics in the meantime.',
    backgroundProcess: 'A newer version is being prepared in the background...',
    generatedBy: 'Generated by Cloudflare MasterClass AI',

    // Chat
    chatTitle: 'Cloudflare Assistant',
    chatPlaceholder: 'Ask a question...',
    chatEmpty: 'Ask about any part of the content.',
    quoteSelection: '+ Quote Selection',

    // Toasts
    toastReady: 'Content Ready',
    toastReadyDesc: 'successfully generated.',
    toastError: 'Error',
    toastErrorDesc: 'could not be generated.',
    toastQueued: 'Added to Queue',
    toastQueuedDesc: 'added to queue for update.',
    toastBulkCat: 'Category Updating',
    toastBulkCatDesc: 'topics added to queue.',
    toastBulkAll: 'Full Refresh Started',
    toastBulkAllDesc: 'topics queued. This may take a while.',
    toastReset: 'Factory Reset Complete',
    toastResetDesc: 'All content reverted to default (fast) state.',
    toastResetProg: 'Progress Reset',
    toastQueueCleared: 'Queue Cleared'
  }
};
